In [1]:
import numpy as np
import pandas as pd

In [2]:
movies= pd.read_csv("tmdb_5000_movies.csv")
credits=pd.read_csv('tmdb_5000_credits.csv')
movies.shape

(4803, 20)

In [3]:
## merging both data set
movies=movies.merge(credits, on='title')

In [4]:
# include all the columns which is needed
movies=movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [5]:
#checking the null values
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [6]:
## delete the rows of overview which is null
movies.dropna(inplace=True)

In [7]:
## checking duplicate data
movies.duplicated().sum()

np.int64(0)

In [8]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [11]:
import ast
def convert1(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter=counter+1
        else:
            break
            
       
    return L

In [12]:
movies['cast']=movies['cast'].apply(convert1)

In [13]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [14]:
import ast
def convert2(obj):
    L=[]
 
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [15]:
movies['crew']=movies['crew'].apply(convert2)

In [16]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [17]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [18]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [19]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ", "") for i in x])

In [20]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]

In [21]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [23]:
movies['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 '[',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'A',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '2',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'A',
 'd',
 'v',
 'e',
 'n',
 't',
 'u',
 'r',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'F',
 'a',
 'n',
 't',
 'a',
 's',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '8',
 '7',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e',
 '',
 'F',
 'i',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 '}',
 ']',
 '[',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '6',
 '3',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'c',
 'u',
 'l',
 't',
 'u',
 'r',
 'e',
 '',
 'c',
 'l',
 'a',
 's',
 'h',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '9',
 '6',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'f',
 'u',
 't',
 'u',
 'r',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '3',
 '8',
 '6',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 'w',
 'a',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '3',
 '8',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 'c',
 'o',
 'l',
 'o',
 'n',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '6',
 '7',
 '9',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'o',
 'c',
 'i',
 'e',
 't',
 'y',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '3',
 '8',
 '0',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '',
 't',
 'r',
 'a',
 'v',
 'e',
 'l',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '6',
 '8',
 '5',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'f',
 'u',
 't',
 'u',
 'r',
 'i',
 's',
 't',
 'i',
 'c',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '8',
 '4',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'r',
 'o',
 'm',
 'a',
 'n',
 'c',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '8',
 '8',
 '2',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'p',
 'a',
 'c',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '9',
 '9',
 '5',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'l',
 'i',
 'e',
 'n',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '1',
 '4',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 't',
 'r',
 'i',
 'b',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '1',
 '5',
 '8',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'l',
 'i',
 'e',
 'n',
 '',
 'p',
 'l',
 'a',
 'n',
 'e',
 't',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '0',
 '9',
 '8',
 '7',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'c',
 'g',
 'i',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '1',
 '3',
 '9',
 '9',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'm',
 'a',
 'r',
 'i',
 'n',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '3',
 '0',
 '6',
 '5',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 's',
 'o',
 'l',
 'd',
 'i',
 'e',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '6',
 '4',
 '3',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'b',
 'a',
 't',
 't',
 'l',
 'e',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '4',
 '7',
 '2',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'l',
 'o',
 'v',
 'e',
 '',
 'a',
 'f',
 'f',
 'a',
 'i',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '6',
 '5',
 '4',
 '3',
 '1',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'a',
 'n',
 't',
 'i',
 '',
 'w',
 'a',
 'r',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '1',
 '9',
 '3',
 '5',
 '5',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'p',
 'o',
 'w',
 'e',
 'r',
 '',
 'r',
 'e',
 'l',
 'a',
 't',
 'i',
 'o',
 'n',
 's',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '0',
 '6',
 '6',
 '9',
 '0',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 'm',
 'i',
 'n',
 'd',
 '',
 'a',
 'n',
 'd',
 '',
 's',
 'o',
 'u',
 'l',
 '"',
 '}',
 ',',
 '',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 '',
 '2',
 '0',
 '9',
 '7',
 '1',
 '4',
 ',',
 '',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 '',
 '"',
 '3',
 'd',
 '"',
 '}',
 ']',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [24]:
new_df=movies[['movie_id', 'title', 'tags']]
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [25]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\91639\AppData\Local\Temp\ipykernel_15192\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [26]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [27]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\91639\AppData\Local\Temp\ipykernel_15192\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [28]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [29]:
## PRE PROCESS IS DONE

In [30]:
## NOW WE USE bAGS OF WORDS METHOD FOR TEXT VECTORIZATION

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000, stop_words="english")

In [32]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [33]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [34]:
for  word in cv.get_feature_names_out():
  print(word)

000
007
10
100
11
12
13
14
15
150
16
17
17th
18
18th
19
1930s
1940s
1944
1950
1950s
1955
1959
1960
1960s
1962
1964
1965
1967
1970s
1971
1972
1973
1974
1976
1979
1980
1980s
1985
1997
1999
19th
20
200
2000
2003
2009
20th
21st
23
24
25
30
300
3d
40
50
500
60
60s
70
70s
aaron
aaroneckhart
abandoned
abducted
abigailbreslin
abilities
ability
able
aboard
abroad
absence
abuse
abusive
academic
academy
accept
accepted
accepts
access
accident
accidental
accidentally
accompanied
accomplish
account
accountant
accused
ace
achieve
act
acting
action
actions
activist
activities
activity
actor
actors
actress
acts
actual
actually
adam
adams
adamsandler
adamshankman
adaptation
adapted
addict
addicted
addiction
adolescent
adopt
adopted
adopts
adrienbrody
adult
adulthood
adults
advantage
adventure
adventures
advertising
advice
affair
affairs
affect
affections
affluent
afghanistan
afraid
africa
african
afterlife
aftermath
age
aged
agency
agenda
agent
agents
aggressive
aging
ago
agree
agrees
ahead
aid
aidanquinn
aided
ailing
air
airport
aka
al
alabama
alan
alaska
albert
alcohol
alcoholic
alecbaldwin
alex
alexkendrick
alfredhitchcock
alfredmolina
ali
alice
alicebraga
alien
aliens
alike
alive
allen
alliance
allied
allies
allow
allowing
allows
ally
alongside
alpacino
alpha
alter
altering
alternate
alternative
alyssa
alzheimer
amanda
amandapeet
amandaseyfried
amateur
amazing
ambassador
amberheard
ambition
ambitious
america
american
americans
amid
amidst
amp
amusement
amy
amyadams
amysmart
ana
anakin
analyst
ancient
anderson
andiemacdowell
andrew
andrewniccol
andy
andyfickman
andygarcía
andyserkis
andytennant
angel
angela
angelabassett
angeles
angelinajolie
angels
anger
anglee
angry
animal
animals
animated
anjelicahuston
ann
anna
annafaris
annakendrick
anne
annehathaway
anneheche
annemoss
annettebening
annie
anniversary
announces
annual
anonymous
answer
answers
anthony
anthonyanderson
anthonyhopkins
anthonymackie
anti
antics
antoinefuqua
antoniobanderas
antonyelchin
apart
apartment
ape
apes
apocalypse
apocalyptic
apparent
apparently
appear
appears
apple
appointed
apprentice
approach
approaches
approaching
april
arab
arch
architect
arctic
area
aren
arena
arise
aristocrat
armed
armored
arms
army
arnold
arnoldschwarzenegger
arrangement
arranges
arrest
arrested
arrival
arrive
arrived
arrives
arriving
arrogant
art
arthur
article
artificial
artist
artistic
artists
arts
ashley
ashleyjudd
ashtonkutcher
asia
aside
ask
asked
asking
asks
aspirations
aspiring
assassin
assassinate
assassination
assassins
assault
assigned
assignment
assist
assistance
assistant
assume
assumes
astronaut
astronauts
asylum
athlete
athletes
atlantic
atomegoyan
attack
attacked
attacks
attempt
attempting
attempts
attend
attending
attends
attention
attitude
attorney
attracted
attraction
attractive
audience
audiences
audition
audreytautou
august
aunt
austin
australia
australian
author
authorities
authority
auto
autobiographical
available
avenge
average
avoid
avoiding
await
awaits
awake
awakens
award
away
awesome
awkward
awry
babe
baby
bachelor
backdrop
backed
background
backgrounds
backyard
bad
badly
bag
bail
baker
balance
ball
ballet
baltimore
band
bandits
banished
bank
banker
bar
barbara
barbrastreisand
barely
bargained
barney
baron
barry
barrylevinson
barrypepper
barrysonnenfeld
bars
base
baseball
based
basement
basketball
batman
battalion
battle
battles
battling
bay
beach
bear
bears
beast
beasts
beat
beats
beautiful
beauty
becky
bed
bedroom
bee
befriends
began
begin
beginning
begins
behavior
beings
belief
beliefs
believe
believed
believes
believing
belong
belongs
beloved
ben
benaffleck
beneath
benfoster
beniciodeltoro
benjamin
benjaminbratt
benkingsley
bennett
benstiller
bent
berlin
best
bet
beth
betrayal
betrayed
bettemidler
better
betty
beverly
bid
big
bigger
biggest
bike
biker
bikers
bilbo
billhader
billionaire
billmurray
billnighy
billpaxton
billpullman
billy
billybobthornton
billycrudup
billycrystal
biographical
biography
biopic
bird
birth
birthday
bishop
bit
bitter
bizarre
black
blackmail
blade
blame
blind
bliss
block
blonde
blood
bloodthirsty
bloody
blow
blue
board
boarding
boat
bob
bobby
bobbyfarrelly
bobhoskins
bodies
body
bodyguard
bold
bomb
bombing
bond
bonds
bonniehunt
book
books
border
bored
boring
born
boss
boston
botched
bound
boundaries
bounty
bourne
bout
box
boxer
boxing
boy
boyfriend
boys
bradleycooper
bradpitt
brain
brand
brandon
brave
break
breakdown
breaking
breaks
brendanfraser
brendangleeson
brent
brettratner
brian
briandepalma
bride
bridge
brief
brielarson
brien
bright
brilliant
bring
bringing
brings
brink
britain
british
brittanymurphy
broadway
broke
broken
brooklyn
brooks
brother
brothers
brought
brown
bruce
brucegreenwood
brucewillis
brutal
brutally
bryansinger
buck
buddies
buddy
budget
build
building
builds
built
bully
bumbling
bunch
buried
burned
burns
bus
bush
business
businessman
bust
busy
butler
butt
buy
buzz
cabin
cable
caesar
cal
caleb
california
called
calling
calls
calm
calvin
came
camera
cameraman
cameras
cameroncrowe
camerondiaz
camgigandet
camp
campaign
campbell
campbellscott
campus
canada
canadian
cancer
candidate
canine
capable
capital
capt
captain
captive
capture
captured
captures
capturing
car
card
care
career
careers
carefree
cares
caretaker
careymulligan
cargo
caribbean
carl
carlagugino
carmen
carol
carolina
carpenter
carrie
carriefisher
carry
carrying
cars
cartel
carter
caryelwes
case
cases
caseyaffleck
cash
casino
cast
castle
cat
catch
catches
cateblanchett
catherine
catherinedeneuve
catherinehardwicke
catherinekeener
catherinezeta
catholic
cats
cattle
caught
cause
caused
causes
causing
cave
cedrictheentertainer
celebrate
celebrated
celebration
celebrity
cell
center
centered
centers
central
centuries
century
certain
chad
chain
challenge
challenged
challenges
champion
championship
chance
change
changed
changes
changing
channingtatum
chaos
chaotic
chapter
character
characters
charge
charged
charismatic
charles
charlie
charliesheen
charlizetheron
charlotte
charm
charming
chase
chased
chases
chazzpalminteri
cheating
chef
chemical
cher
chevychase
chicago
chief
child
childhood
children
chilling
china
chinese
chip
chiwetelejiofor
chloe
chloëgracemoretz
chloësevigny
choice
choices
choose
chosen
chowyun
chris
chriscolumbus
chriscooper
chrisevans
chrishemsworth
chrisklein
chrispine
chrisrock
christ
christian
christianbale
christianslater
christinaapplegate
christinaricci
christine
christmas
christopher
christopherlambert
christopherlloyd
christophernolan
christopherplummer
christopherwalken
christophwaltz
chrisweitz
chronicle
chronicles
chuck
church
cia
ciaránhinds
cillianmurphy
cindy
circle
circuit
circumstances
circus
cities
citizens
city
civil
civilian
civilization
claim
claiming
claims
claire
clairedanes
claireforlani
clan
clark
clash
class
classes
classic
classmate
classmates
claudevandamme
clay
clean
clear
clerk
client
clients
climb
climbing
clinteastwood
clique
cliveowen
clock
clone
close
closed
closer
closing
closure
club
clubs
clue
clueless
clues
clutches
coach
coast
coastal
cocaine
cocky
code
cody
cohen
col
cold
cole
colehauser
coleridge
colin
colinfarrell
colinfirth
collapse
collapses
colleague
colleagues
collect
collection
collective
collector
college
collide
collins
collision
colonel
colony
color
colorado
colorful
coma
combat
combination
combined
come
comeback
comedian
comedic
comedy
comes
comfort
comic
comics
coming
command
commander
commanding
commit
commitment
commits
committed
common
communication
communist
community
companion
companions
company
compete
competing
competition
competitive
complete
completely
complex
complicated
complications
compton
compulsive
computer
conan
concerning
concert
conclusion
condition
conditions
confidence
confident
conflict
conflicts
confront
confronted
confronts
confused
connect
connected
connecticut
connection
connections
connects
connell
connie
connienielsen
connor
conquer
conrad
conscience
consequences
conservative
considered
considers
conspiracy
conspire
constant
constantly
construction
consumed
contact
contain
containing
contains
contemporary
contend
contest
continent
continue
continues
continuing
contract
control
controlled
controlling
controversial
convention
converge
convict
convicted
convicts
convince
convinced
convinces
cook
cool
cooper
cop
cope
cops
core
corleone
corner
corners
corporate
corporation
corpse
corrupt
corruption
cosmos
cost
couldn
count
countless
countries
country
countryside
county
coup
couple
couples
courage
courageous
course
court
courteneycox
courts
cousin
cover
covert
cowboy
crack
craft
craig
crane
crash
crashes
crashing
crazed
crazy
create
created
creates
creation
creative
creator
creature
creatures
credit
creepy
crew
crime
crimes
criminal
criminals
crisis
critical
crocodile
crook
crooked
cross
crossed
crosses
crossroads
crowd
crown
cruel
cruelty
cruise
crush
crystal
cuba
cubagoodingjr
cult
cultural
culture
cunning
cup
cure
curious
current
currently
curse
cursed
curtishanson
cusp
custody
customers
cut
cuts
cutthroat
cynical
dad
daily
dakotafanning
dale
damage
damon
dan
danaykroyd
dance
dancer
dancing
danger
dangerous
dangers
daniel
danielcraig
danielday
danielradcliffe
danish
danny
dannyboyle
dannydevito
dannyglover
dannymcbride
darcy
daring
dark
darkest
darkness
darrenaronofsky
darylhannah
dashing
date
dates
dating
daughter
daughters
dave
david
davidarquette
davidcronenberg
davidduchovny
davidfincher
davidgordongreen
davidmorse
davido
davidschwimmer
davidspade
davidthewlis
davis
daxshepard
day
days
dc
dea
dead
deadliest
deadly
deal
dealer
dealers
dealing
deals
dean
death
deaths
debt
debut
decade
decades
deceased
deceit
deception
decide
decided
decides
decision
decisions
dedicated
deeds
deep
deeper
deeply
defeat
defeated
defeating
defend
defense
deforestkelley
deke
deliver
delivers
delivery
demand
demanding
demands
demimoore
demon
demonic
demons
deniserichards
denisleary
dennis
dennisdugan
dennishopper
dennisquaid
denzelwashington
department
depicts
depressed
depression
depths
deputy
deranged
derek
derekluke
descend
descends
desert
deserted
designed
desire
desires
desolate
despair
desperate
desperately
despite
destination
destined
destiny
destroy
destroyed
destroying
destruction
destructive
details
detective
detectives
detention
determination
determine
determined
detroit
devastating
develop
developed
developer
developing
develops
device
devil
devious
devoted
diabolical
diagnosed
dialogue
diamond
diana
diane
dianekeaton
dianekruger
dianelane
dick
dictator
did
didn
die
died
diego
dies
differences
different
difficult
digging
diner
dinner
dinosaurs
dire
directed
direction
director
dirt
dirty
disappear
disappearance
disappeared
disappears
disaster
disastrous
discover
discovered
discovering
discovers
discovery
disease
disfigured
disgraced
disguise
disillusioned
disney
disorder
dispatched
distant
district
disturbed
disturbing
ditch
diva
divided
division
divorce
divorced
dna
doc
doctor
doctors
document
documentary
documents
does
doesn
dog
dogs
doing
doll
dollar
dollars
dolphin
dolphins
dolphlundgren
domestic
domination
don
donaldpetrie
donaldsutherland
doncheadle
donnell
doomed
door
doorstep
dorothy
double
doubt
doubts
doug
douglas
dougliman
dr
dracula
drag
dragon
drama
dramatic
draw
drawing
drawn
draws
dre
dream
dreams
dress
drew
drewbarrymore
drifter
drink
drinking
drive
driven
driver
drives
driving
drop
drug
drugs
drunk
drunken
du
dubbed
dude
duke
dumped
dumps
duncan
duo
dustinhoffman
dutch
dutton
duty
dwaynejohnson
dwindling
dying
dylan
dynamic
dynasty
eager
earlier
early
earn
earned
earth
easily
east
eastern
easy
eating
eccentric
economic
economy
ed
eddie
eddiegriffin
eddiemurphy
edgar
edge
edharris
editor
education
edward
edwardburns
edwardnorton
edwardzwick
effort
efforts
egg
ego
egypt
egyptian
el
elaborate
elderly
election
elements
elena
eliaskoteas
elijahwood
eliminate
elisabethshue
elite
elizabeth
elizabethbanks
ella
ellenburstyn
ellenpage
ellie
elliot
elliott
ellis
elude
elusive
elves
elvis
embark
embarking
embarks
embroiled
emerge
emergency
emerges
emilehirsch
emily
emilyblunt
emilymortimer
emilywatson
emma
emmaroberts
emmastone
emmathompson
emmawatson
emotional
emotionally
emotions
emperor
empire
employee
employees
employer
employs
encounter
encounters
end
ended
ending
endless
ends
enduring
enemies
enemy
energy
enforcement
engaged
engineer
england
english
enigmatic
enjoy
enlist
enlists
enormous
ensues
ensure
entangled
enter
enterprise
enters
entertaining
entire
entirely
entity
environment
environmental
epic
epidemic
episode
equal
equally
era
eric
ericbana
erin
ernest
erotic
erupts
escape
escaped
escapes
escaping
escort
especially
espionage
establish
established
establishment
estate
esteem
estranged
eternal
ethan
ethanhawke
eugenelevy
europe
european
eva
evade
evamendes
evanrachelwood
eve
evening
event
events
eventually
evers
everybody
everyday
evidence
evil
ewanmcgregor
ex
exact
exactly
examines
exchange
excitement
exciting
exclusive
executed
execution
executive
exist
existed
existence
exists
exorcism
exorcisms
exotic
expectations
expected
expects
expedition
experience
experienced
experiences
experiencing
experiment
expert
explain
explodes
exploits
explorers
explores
exploring
explosion
explosive
expose
exposed
exposes
extra
extraordinary
extraterrestrial
extreme
extremely
eye
eyes
face
faced
faces
facility
facing
fact
factions
factory
fail
failed
failing
fails
fairy
faith
fake
fall
fallen
falling
falls
fame
famed
families
family
famkejanssen
famous
fan
fans
fantasies
fantastic
fantasy
far
farm
farmer
fascinated
fashion
fast
faster
fat
fatal
fate
fateful
father
favorite
fbi
fear
fearless
fears
fearsome
feature
features
featuring
federal
feel
feeling
feelings
feels
feet
fellow
female
females
fend
ferocious
festival
fi
fiancee
fiancé
fiancée
fiction
fictional
field
fields
fierce
fifth
fight
fighter
fighters
fighting
fights
figure
figures
filled
film
filmed
filming
filmmaker
filmmakers
films
final
finale
finally
financial
finding
finds
fine
finish
finished
finn
fired
firm
fish
fisherman
fishing
fit
fix
flame
fledgling
flee
fleeing
flees
flesh
flight
fling
flint
floor
florida
fly
flying
flynn
focus
focused
focuses
foil
foley
folk
follow
followed
following
follows
food
foot
footage
football
forbidden
force
forced
forces
forcing
ford
foreign
forest
forestwhitaker
forever
forget
forgiveness
form
formed
formidable
forms
formula
fortune
forward
foster
fought
foul
fourteen
fourth
fox
framed
france
franchise
francis
francisco
francisfordcoppola
frank
frankcoraci
frankenstein
frankie
frankiemuniz
franklangella
frankoz
fraternity
fraud
freak
fred
freddie
freddieprinzejr
freddy
free
freed
freedom
freeman
french
fresh
freshman
friend
friendly
friends
friendship
frightening
frontier
frozen
frustrated
fu
fueled
fugitive
fulfill
fully
fun
fund
funds
funeral
funny
furious
future
futuristic
gabrielbyrne
gadgets
gaelgarcíabernal
gain
galactic
galaxy
gale
gambler
gambling
game
games
gandhi
gang
gangs
gangster
gangsters
garden
garretthedlund
garrymarshall
gary
garyfleder
garygray
garyoldman
garysinise
gas
gates
gather
gave
gay
geenadavis
gene
genehackman
general
generals
generation
generations
genetic
genetically
genius
genre
gentle
geoffreyrush
george
georgea
georgeclooney
georgemiller
georgia
gerardbutler
german
germans
germany
gerry
getaway
gets
getting
ghetto
ghost
ghosts
giant
giants
gift
gifted
gig
giovanniribisi
girl
girlfriend
girlfriends
girls
given
gives
giving
glamorous
glass
glenn
glennclose
global
globe
glory
goal
god
gods
goes
going
gold
golden
goldiehawn
golf
gone
good
goons
gordon
goreverbinski
gorgeous
got
gotham
gotten
government
governor
grace
grade
gradually
graduate
graduation
graham
grand
granddaughter
grandfather
grandmother
granny
grant
graphic
grasp
grave
great
greater
greatest
greece
greed
greedy
greek
green
greg
gregkinnear
gregorypeck
grew
grief
grieving
griffin
grim
grip
grisly
gritty
ground
group
groups
grow
growing
grown
grows
gruesome
guard
guardian
guards
guest
guests
guidance
guide
guilt
guilty
gun
gunman
guns
gusvansant
guy
guypearce
guyritchie
guys
gwynethpaltrow
hacker
hair
haleyjoelosment
half
hall
halleberry
halloween
han
hand
handed
handle
hands
handsome
hang
hanging
hangs
hankazaria
hannah
hansel
hapless
happen
happened
happening
happens
happily
happiness
happy
hara
harbor
harbors
hard
harder
harlem
harmony
harold
haroldramis
harriet
harris
harrison
harrisonford
harrowing
harry
harsh
hart
harvard
harvey
harveykeitel
hasn
hatches
hate
hatred
haunt
haunted
haunting
haven
having
havoc
hawaii
hawkins
haydenchristensen
haydenpanettiere
head
headed
heading
headquarters
heads
health
hear
heard
hears
heart
hearted
hearts
heather
heathergraham
heathledger
heaven
heavily
heavy
heir
heiress
heist
held
helen
helenabonhamcarter
helenhunt
helenmirren
hell
help
helped
helping
helps
henry
henrythomas
hero
heroes
heroic
heroin
hidden
hide
hides
hiding
high
higher
highest
highlands
highly
hilarious
hilariously
hilaryduff
hilaryswank
hill
hills
hip
hire
hired
hires
historic
historical
history
hit
hitler
hitman
hits
ho
hockey
hoffman
hogwarts
hold
holden
holding
holds
hole
holiday
holly
hollywood
holmes
holy
home
homeland
homeless
homes
hometown
homicidal
homicide
honey
honeymoon
hong
honor
hood
hook
hop
hope
hopedavis
hopelessly
hopes
hoping
hopkins
hopper
horrible
horrific
horrifying
horror
horrors
horse
hospital
host
hostage
hostile
hot
hotel
hotshot
hour
hours
house
housewife
housing
howard
hud
huge
hugh
hughes
hughgrant
hughjackman
human
humanity
humankind
humans
humor
hundreds
hunger
hungry
hunt
hunted
hunter
hunters
hunting
hunts
husband
hustler
hysterical
hyun
ianholm
ianmckellen
ice
icecube
iconic
idea
idealistic
ideas
identities
identity
idol
idyllic
ignoring
ii
iii
il
ill
illegal
illicit
illness
image
imaginary
imagination
imagined
immediately
immense
immigrant
immigrants
immortal
impact
impending
imperial
important
impossible
impress
imprisoned
inadvertently
incident
incidents
include
includes
including
incompetent
increasingly
incredible
independence
independent
india
indian
indiana
indians
indie
individual
industry
inept
inevitable
inexplicably
infamous
infant
infected
infiltrate
influence
influential
informant
information
inhabitants
inherited
inherits
initially
injured
injury
injustice
inmates
inner
innocence
innocent
insane
insanity
inside
insists
inspector
inspiration
inspire
inspired
inspires
inspiring
installment
instant
instantly
instead
institution
instructor
insurance
intelligence
intelligent
intended
intends
intense
intent
intention
intentions
interested
intergalactic
internal
international
internet
intertwine
interview
interviews
intimate
intrepid
intricate
intrigue
introduces
invade
invaders
invading
invasion
invention
inventor
investigate
investigates
investigating
investigation
investigator
investment
invisible
invitation
invited
invites
involved
involves
involving
iowa
ira
iranian
iraq
irene
irish
irreverent
ishmael
island
isn
isolated
israel
israeli
issues
italian
italy
ivanreitman
ivy
jack
jackass
jackblack
jackie
jackiechan
jacknicholson
jackson
jacob
jacques
jadapinkettsmith
jail
jake
jakegyllenhaal
james
jamescaan
jamescameron
jamesfranco
jamesivory
jamesmangold
jamesmarsden
jamesmcavoy
jameswan
jameswoods
jamie
jamiebell
jamiefoxx
jamieleecurtis
jan
jane
japan
japanese
jaredleto
jason
jasonbateman
jasonbiggs
jasonlee
jasonschwartzman
jasonsegel
jasonstatham
javierbardem
jay
jaychandrasekhar
jayroach
jealous
jealousy
jean
jeanreno
jedi
jeff
jeffbridges
jeffdaniels
jeffgoldblum
jeffreywright
jennifer
jenniferaniston
jenniferconnelly
jennifergarner
jenniferjasonleigh
jenniferlawrence
jenniferlopez
jenniferlovehewitt
jenny
jeremyirons
jeremynortham
jeremyrenner
jerry
jersey
jerusalem
jess
jesse
jessebradford
jesseeisenberg
jessica
jessicaalba
jessicabiel
jessicachastain
jesus
jetli
jewel
jewish
jews
jigsaw
jill
jim
jimbroadbent
jimcarrey
jimcaviezel
jimmy
jin
joan
joanallen
joanchen
joancusack
joaquinphoenix
job
jobs
jodiefoster
joe
joel
joelcoen
joeledgerton
joelschumacher
joepesci
joey
john
johnc
johncarpenter
johncusack
johngoodman
johnhurt
johnkrasinski
johnleguizamo
johnmalkovich
johnmctiernan
johnny
johnnydepp

In [35]:
import nltk ## it is a natural language toolkit
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [36]:
ps.stem('loved')

'love'

In [37]:
def stem(text):## doubt 4
    y=[]

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [38]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\91639\AppData\Local\Temp\ipykernel_15192\3293759246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [39]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [40]:
## distance is inversely proportional to similarity
## we just calculate angles between two vectors(film)
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
cosine_similarity(vectors)

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.04225771, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.03450328, 0.        ,
        0.        ],
       ...,
       [0.        , 0.04225771, 0.03450328, ..., 1.        , 0.055577  ,
        0.02942449],
       [0.        , 0.        , 0.        , ..., 0.055577  , 1.        ,
        0.05723638],
       [0.        , 0.        , 0.        , ..., 0.02942449, 0.05723638,
        1.        ]], shape=(4806, 4806))

In [42]:
similarity=cosine_similarity(vectors)

In [43]:
similarity[1]

array([0.        , 1.        , 0.        , ..., 0.04225771, 0.        ,
       0.        ], shape=(4806,))

In [44]:
sorted(similarity[0])[-10:-1]

[np.float64(0.11547005383792514),
 np.float64(0.12433397443204182),
 np.float64(0.12524485821702988),
 np.float64(0.14322297480788657),
 np.float64(0.1438389904456152),
 np.float64(0.16129556770910236),
 np.float64(0.17770466332772766),
 np.float64(0.18257418583505533),
 np.float64(0.24494897427831777)]

In [45]:
list(enumerate(similarity[0]))

[(0, np.float64(0.9999999999999998)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.03688555567816587)),
 (4, np.float64(0.0)),
 (5, np.float64(0.046373889576016826)),
 (6, np.float64(0.0)),
 (7, np.float64(0.04714045207910316)),
 (8, np.float64(0.0)),
 (9, np.float64(0.0)),
 (10, np.float64(0.0)),
 (11, np.float64(0.04564354645876383)),
 (12, np.float64(0.0)),
 (13, np.float64(0.0)),
 (14, np.float64(0.0)),
 (15, np.float64(0.0)),
 (16, np.float64(0.0)),
 (17, np.float64(0.0)),
 (18, np.float64(0.0)),
 (19, np.float64(0.0)),
 (20, np.float64(0.0)),
 (21, np.float64(0.0)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.0)),
 (25, np.float64(0.032791291789197645)),
 (26, np.float64(0.0563436169819011)),
 (27, np.float64(0.07874992309581577)),
 (28, np.float64(0.0)),
 (29, np.float64(0.03892494720807615)),
 (30, np.float64(0.0)),
 (31, np.float64(0.06900655593423542)),
 (32, np.float64(0.0)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0)),
 (35, np.float64(0.0)),
 (36, np.float64(0.09589266029707681)),
 (37, np.float64(0.0)),
 (38, np.float64(0.0)),
 (39, np.float64(0.0)),
 (40, np.float64(0.0)),
 (41, np.float64(0.0)),
 (42, np.float64(0.0)),
 (43, np.float64(0.047946330148538406)),
 (44, np.float64(0.0)),
 (45, np.float64(0.07532435771547094)),
 (46, np.float64(0.0)),
 (47, np.float64(0.07453559924999299)),
 (48, np.float64(0.0)),
 (49, np.float64(0.0)),
 (50, np.float64(0.0)),
 (51, np.float64(0.0)),
 (52, np.float64(0.0)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.0)),
 (56, np.float64(0.0)),
 (57, np.float64(0.0)),
 (58, np.float64(0.0)),
 (59, np.float64(0.0)),
 (60, np.float64(0.0)),
 (61, np.float64(0.0)),
 (62, np.float64(0.0)),
 (63, np.float64(0.0)),
 (64, np.float64(0.0)),
 (65, np.float64(0.0)),
 (66, np.float64(0.0)),
 (67, np.float64(0.0)),
 (68, np.float64(0.06454972243679027)),
 (69, np.float64(0.0)),
 (70, np.float64(0.0)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.09274777915203365)),
 (75, np.float64(0.0)),
 (76, np.float64(0.0)),
 (77, np.float64(0.0)),
 (78, np.float64(0.0)),
 (79, np.float64(0.0)),
 (80, np.float64(0.0)),
 (81, np.float64(0.0)),
 (82, np.float64(0.0)),
 (83, np.float64(0.0816496580927726)),
 (84, np.float64(0.0)),
 (85, np.float64(0.0)),
 (86, np.float64(0.0)),
 (87, np.float64(0.05504818825631802)),
 (88, np.float64(0.0)),
 (89, np.float64(0.024618298195866545)),
 (90, np.float64(0.0)),
 (91, np.float64(0.050636968354183326)),
 (92, np.float64(0.0)),
 (93, np.float64(0.0)),
 (94, np.float64(0.06900655593423542)),
 (95, np.float64(0.0)),
 (96, np.float64(0.0)),
 (97, np.float64(0.0)),
 (98, np.float64(0.0)),
 (99, np.float64(0.0)),
 (100, np.float64(0.0)),
 (101, np.float64(0.0)),
 (102, np.float64(0.03513641844631532)),
 (103, np.float64(0.0)),
 (104, np.float64(0.0)),
 (105, np.float64(0.0)),
 (106, np.float64(0.0)),
 (107, np.float64(0.03984095364447979)),
 (108, np.float64(0.0)),
 (109, np.float64(0.0)),
 (110, np.float64(0.0)),
 (111, np.float64(0.0)),
 (112, np.float64(0.0)),
 (113, np.float64(0.0)),
 (114, np.float64(0.0)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (117, np.float64(0.0)),
 (118, np.float64(0.0)),
 (119, np.float64(0.0)),
 (120, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.0)),
 (124, np.float64(0.0)),
 (125, np.float64(0.0)),
 (126, np.float64(0.0)),
 (127, np.float64(0.03450327796711771)),
 (128, np.float64(0.0)),
 (129, np.float64(0.0)),
 (130, np.float64(0.0)),
 (131, np.float64(0.046373889576016826)),
 (132, np.float64(0.0)),
 (133, np.float64(0.0)),
 (134, np.float64(0.07161148740394328)),
 (135, np.float64(0.0)),
 (136, np.float64(0.0)),
 (137, np.float64(0.027066598098038335)),
 (138, np.float64(0.0)),
 (139, np.float64(0.047946330148538406)),
 (140, np.float64(0.04188539082916955)),
 (141, np.float64(0.0)),
 (142, np.float64(0.0)),
 (143, np.float64(0.0)),
 (144, np.float64(0.0)),
 (145, np.float64(0.0)),
 (146, np.float64(0.0)),
 (147, np.float64(0.0)),
 (148, np.float64(0.06454972243679027)),
 (149, np.float64(0.08606629658238703)),
 (150, np.float64(0.10954451150103323)),
 (151, np.float64(0.18257418583505533)),
 (152, np.float64(0.0)),
 (153, np.float64(0.03615507630310936)),
 (154, np.float64(0.0)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0)),
 (157, np.float64(0.0)),
 (158, np.float64(0.0)),
 (159, np.float64(0.0)),
 (160, np.float64(0.0)),
 (161, np.float64(0.0)),
 (162, np.float64(0.0)),
 (163, np.float64(0.0)),
 (164, np.float64(0.0)),
 (165, np.float64(0.0)),
 (166, np.float64(0.0)),
 (167, np.float64(0.0)),
 (168, np.float64(0.0)),
 (169, np.float64(0.0)),
 (170, np.float64(0.04188539082916955)),
 (171, np.float64(0.0)),
 (172, np.float64(0.0)),
 (173, np.float64(0.0)),
 (174, np.float64(0.053838190205816545)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (179, np.float64(0.0)),
 (180, np.float64(0.0)),
 (181, np.float64(0.0)),
 (182, np.float64(0.0)),
 (183, np.float64(0.0)),
 (184, np.float64(0.04564354645876383)),
 (185, np.float64(0.0)),
 (186, np.float64(0.0)),
 (187, np.float64(0.0)),
 (188, np.float64(0.0)),
 (189, np.float64(0.0)),
 (190, np.float64(0.0)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.0)),
 (194, np.float64(0.0)),
 (195, np.float64(0.0)),
 (196, np.float64(0.0)),
 (197, np.float64(0.0)),
 (198, np.float64(0.0)),
 (199, np.float64(0.08989331499509894)),
 (200, np.float64(0.0)),
 (201, np.float64(0.0)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.0)),
 (205, np.float64(0.0)),
 (206, np.float64(0.03892494720807615)),
 (207, np.float64(0.0)),
 (208, np.float64(0.0)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.0)),
 (212, np.float64(0.0)),
 (213, np.float64(0.04494665749754947)),
 (214, np.float64(0.0)),
 (215, np.float64(0.0)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.0)),
 (220, np.float64(0.0)),
 (221, np.float64(0.0)),
 (222, np.float64(0.03580574370197164)),
 (223, np.float64(0.0)),
 (224, np.float64(0.0)),
 (225, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.0)),
 (228, np.float64(0.04244763599780088)),
 (229, np.float64(0.0)),
 (230, np.float64(0.03513641844631532)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.0)),
 (234, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.06454972243679027)),
 (237, np.float64(0.0)),
 (238, np.float64(0.0)),
 (239, np.float64(0.03651483716701107)),
 (240, np.float64(0.0)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.0)),
 (244, np.float64(0.0)),
 (245, np.float64(0.0)),
 (246, np.float64(0.0)),
 (247, np.float64(0.0)),
 (248, np.float64(0.0)),
 (249, np.float64(0.0)),
 (250, np.float64(0.0)),
 (251, np.float64(0.0)),
 (252, np.float64(0.0)),
 (253, np.float64(0.0)),
 (254, np.float64(0.0)),
 (255, np.float64(0.0)),
 (256, np.float64(0.0)),
 (257, np.float64(0.0)),
 (258, np.float64(0.0)),
 (259, np.float64(0.0)),
 (260, np.float64(0.0)),
 (261, np.float64(0.0)),
 (262, np.float64(0.0)),
 (263, np.float64(0.0)),
 (264, np.float64(0.0)),
 (265, np.float64(0.0)),
 (266, np.float64(0.0)),
 (267, np.float64(0.0)),
 (268, np.float64(0.0)),
 (269, np.float64(0.0)),
 (270, np.float64(0.051639777949432225)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.0)),
 (275, np.float64(0.06454972243679027)),
 (276, np.float64(0.0)),
 (277, np.float64(0.03984095364447979)),
 (278, np.float64(0.0)),
 (279, np.float64(0.04564354645876383)),
 (280, np.float64(0.0)),
 (281, np.float64(0.08989331499509894)),
 (282, np.float64(0.053838190205816545)),
 (283, np.float64(0.0)),
 (284, np.float64(0.0)),
 (285, np.float64(0.0)),
 (286, np.float64(0.0)),
 (287, np.float64(0.0)),
 (288, np.float64(0.0)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0)),
 (291, np.float64(0.0)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.0)),
 (295, np.float64(0.0)),
 (296, np.float64(0.0)),
 (297, np.float64(0.0)),
 (298, np.float64(0.0)),
 (299, np.float64(0.0)),
 (300, np.float64(0.0)),
 (301, np.float64(0.03580574370197164)),
 (302, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.0)),
 (305, np.float64(0.0)),
 (306, np.float64(0.0)),
 (307, np.float64(0.05536365323582664)),
 (308, np.float64(0.0)),
 (309, np.float64(0.0)),
 (310, np.float64(0.0)),
 (311, np.float64(0.09938079899999065)),
 (312, np.float64(0.08989331499509894)),
 (313, np.float64(0.06666666666666665)),
 (314, np.float64(0.0)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.0)),
 (320, np.float64(0.0)),
 (321, np.float64(0.0)),
 (322, np.float64(0.0)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0)),
 (325, np.float64(0.0)),
 (326, np.float64(0.0)),
 (327, np.float64(0.0)),
 (328, np.float64(0.0)),
 (329, np.float64(0.0)),
 (330, np.float64(0.0)),
 (331, np.float64(0.0)),
 (332, np.float64(0.0)),
 (333, np.float64(0.0)),
 (334, np.float64(0.0)),
 (335, np.float64(0.0)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.0)),
 (340, np.float64(0.0)),
 (341, np.float64(0.0)),
 (342, np.float64(0.03227486121839514)),
 (343, np.float64(0.03806934938134405)),
 (344, np.float64(0.0)),
 (345, np.float64(0.0)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.0)),
 (349, np.float64(0.0)),
 (350, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.0)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0)),
 (355, np.float64(0.0)),
 (356, np.float64(0.0)),
 (357, np.float64(0.0)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (361, np.float64(0.0)),
 (362, np.float64(0.0)),
 (363, np.float64(0.0)),
 (364, np.float64(0.0)),
 (365, np.float64(0.050636968354183326)),
 (366, np.float64(0.0)),
 (367, np.float64(0.0)),
 (368, np.float64(0.0)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (372, np.float64(0.047946330148538406)),
 (373, np.float64(0.06900655593423542)),
 (374, np.float64(0.0)),
 (375, np.float64(0.0)),
 (376, np.float64(0.0)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0)),
 (384, np.float64(0.0)),
 (385, np.float64(0.0)),
 (386, np.float64(0.0)),
 (387, np.float64(0.0)),
 (388, np.float64(0.0)),
 (389, np.float64(0.0)),
 (390, np.float64(0.0)),
 (391, np.float64(0.0)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.0)),
 (395, np.float64(0.0)),
 (396, np.float64(0.0)),
 (397, np.float64(0.0)),
 (398, np.float64(0.0)),
 (399, np.float64(0.0)),
 (400, np.float64(0.0)),
 (401, np.float64(0.0)),
 (402, np.float64(0.0)),
 (403, np.float64(0.0)),
 (404, np.float64(0.06262242910851494)),
 (405, np.float64(0.0)),
 (406, np.float64(0.03849001794597505)),
 (407, np.float64(0.0)),
 (408, np.float64(0.0)),
 (409, np.float64(0.0)),
 (410, np.float64(0.0)),
 (411, np.float64(0.0)),
 (412, np.float64(0.0408248290463863)),
 (413, np.float64(0.0)),
 (414, np.float64(0.0)),
 (415, np.float64(0.0)),
 (416, np.float64(0.0)),
 (417, np.float64(0.0)),
 (418, np.float64(0.0)),
 (419, np.float64(0.0)),
 (420, np.float64(0.04494665749754947)),
 (421, np.float64(0.0)),
 (422, np.float64(0.0)),
 (423, np.float64(0.0)),
 (424, np.float64(0.0)),
 (425, np.float64(0.0)),
 (426, np.float64(0.0)),
 (427, np.float64(0.0)),
 (428, np.float64(0.0)),
 (429, np.float64(0.0)),
 (430, np.float64(0.049690399499995326)),
 (431, np.float64(0.0)),
 (432, np.float64(0.04564354645876383)),
 (433, np.float64(0.0)),
 (434, np.float64(0.0)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.0)),
 (440, np.float64(0.0)),
 (441, np.float64(0.0)),
 (442, np.float64(0.0)),
 (443, np.float64(0.0)),
 (444, np.float64(0.0)),
 (445, np.float64(0.0)),
 (446, np.float64(0.0)),
 (447, np.float64(0.0)),
 (448, np.float64(0.0)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.050636968354183326)),
 (455, np.float64(0.0)),
 (456, np.float64(0.04188539082916955)),
 (457, np.float64(0.0)),
 (458, np.float64(0.0)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.06085806194501846)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.06262242910851494)),
 (467, np.float64(0.037267799624996496)),
 (468, np.float64(0.0)),
 (469, np.float64(0.0)),
 (470, np.float64(0.0)),
 (471, np.float64(0.0)),
 (472, np.float64(0.0)),
 (473, np.float64(0.047946330148538406)),
 (474, np.float64(0.0)),
 (475, np.float64(0.04188539082916955)),
 (476, np.float64(0.0)),
 (477, np.float64(0.0)),
 (478, np.float64(0.0)),
 (479, np.float64(0.0)),
 (480, np.float64(0.0)),
 (481, np.float64(0.0)),
 (482, np.float64(0.0)),
 (483, np.float64(0.06085806194501846)),
 (484, np.float64(0.0)),
 (485, np.float64(0.0)),
 (486, np.float64(0.0)),
 (487, np.float64(0.07161148740394328)),
 (488, np.float64(0.03202563076101743)),
 (489, np.float64(0.0)),
 (490, np.float64(0.0)),
 (491, np.float64(0.0)),
 (492, np.float64(0.0)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.07161148740394328)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0)),
 (499, np.float64(0.0)),
 (500, np.float64(0.0)),
 (501, np.float64(0.0)),
 (502, np.float64(0.043033148291193514)),
 (503, np.float64(0.0)),
 (504, np.float64(0.0)),
 (505, np.float64(0.0)),
 (506, np.float64(0.0)),
 (507, np.float64(0.08489527199560176)),
 (508, np.float64(0.0)),
 (509, np.float64(0.0)),
 (510, np.float64(0.0)),
 (511, np.float64(0.0)),
 (512, np.float64(0.0)),
 (513, np.float64(0.04879500364742665)),
 (514, np.float64(0.0)),
 (515, np.float64(0.0)),
 (516, np.float64(0.0)),
 (517, np.float64(0.0)),
 (518, np.float64(0.0)),
 (519, np.float64(0.0)),
 (520, np.float64(0.0)),
 (521, np.float64(0.0)),
 (522, np.float64(0.0)),
 (523, np.float64(0.0)),
 (524, np.float64(0.0)),
 (525, np.float64(0.0)),
 (526, np.float64(0.0)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.16129556770910236)),
 (530, np.float64(0.0)),
 (531, np.float64(0.0)),
 (532, np.float64(0.0)),
 (533, np.float64(0.0)),
 (534, np.float64(0.0)),
 (535, np.float64(0.046373889576016826)),
 (536, np.float64(0.0)),
 (537, np.float64(0.0)),
 (538, np.float64(0.0)),
 (539, np.float64(0.06085806194501846)),
 (540, np.float64(0.0)),
 (541, np.float64(0.0)),
 (542, np.float64(0.0)),
 (543, np.float64(0.0)),
 (544, np.float64(0.0)),
 (545, np.float64(0.0)),
 (546, np.float64(0.0)),
 (547, np.float64(0.0)),
 (548, np.float64(0.0)),
 (549, np.float64(0.043033148291193514)),
 (550, np.float64(0.0)),
 (551, np.float64(0.0)),
 (552, np.float64(0.0)),
 (553, np.float64(0.0)),
 (554, np.float64(0.0)),
 (555, np.float64(0.0)),
 (556, np.float64(0.0)),
 (557, np.float64(0.049690399499995326)),
 (558, np.float64(0.0)),
 (559, np.float64(0.0)),
 (560, np.float64(0.0)),
 (561, np.float64(0.0)),
 (562, np.float64(0.0)),
 (563, np.float64(0.0)),
 (564, np.float64(0.0)),
 (565, np.float64(0.0)),
 (566, np.float64(0.0)),
 (567, np.float64(0.0)),
 (568, np.float64(0.1126872339638022)),
 (569, np.float64(0.0)),
 (570, np.float64(0.0778498944161523)),
 (571, np.float64(0.0)),
 (572, np.float64(0.0)),
 (573, np.float64(0.0)),
 (574, np.float64(0.0)),
 (575, np.float64(0.0)),
 (576, np.float64(0.0)),
 (577, np.float64(0.0)),
 (578, np.float64(0.0)),
 (579, np.float64(0.0)),
 (580, np.float64(0.0)),
 (581, np.float64(0.05773502691896257)),
 (582, np.float64(0.050636968354183326)),
 (583, np.float64(0.0)),
 (584, np.float64(0.0)),
 (585, np.float64(0.0)),
 (586, np.float64(0.0)),
 (587, np.float64(0.04879500364742665)),
 (588, np.float64(0.046373889576016826)),
 (589, np.float64(0.0)),
 (590, np.float64(0.0)),
 (591, np.float64(0.0)),
 (592, np.float64(0.0)),
 (593, np.float64(0.0)),
 (594, np.float64(0.0)),
 (595, np.float64(0.04188539082916955)),
 (596, np.float64(0.0408248290463863)),
 (597, np.float64(0.0)),
 (598, np.float64(0.0)),
 (599, np.float64(0.028867513459481284)),
 (600, np.float64(0.0)),
 (601, np.float64(0.0)),
 (602, np.float64(0.0)),
 (603, np.float64(0.0)),
 (604, np.float64(0.0)),
 (605, np.float64(0.0)),
 (606, np.float64(0.0)),
 (607, np.float64(0.0)),
 (608, np.float64(0.0)),
 (609, np.float64(0.0)),
 (610, np.float64(0.0)),
 (611, np.float64(0.0)),
 (612, np.float64(0.0)),
 (613, np.float64(0.0)),
 (614, np.float64(0.06454972243679027)),
 (615, np.float64(0.0)),
 (616, np.float64(0.0)),
 (617, np.float64(0.06454972243679027)),
 (618, np.float64(0.0)),
 (619, np.float64(0.0)),
 (620, np.float64(0.0)),
 (621, np.float64(0.0)),
 (622, np.float64(0.0)),
 (623, np.float64(0.0)),
 (624, np.float64(0.0)),
 (625, np.float64(0.0)),
 (626, np.float64(0.06900655593423542)),
 (627, np.float64(0.0)),
 (628, np.float64(0.0)),
 (629, np.float64(0.0)),
 (630, np.float64(0.0)),
 (631, np.float64(0.0)),
 (632, np.float64(0.04564354645876383)),
 (633, np.float64(0.0)),
 (634, np.float64(0.05773502691896257)),
 (635, np.float64(0.04714045207910316)),
 (636, np.float64(0.0)),
 (637, np.float64(0.05773502691896257)),
 (638, np.float64(0.0)),
 (639, np.float64(0.0)),
 (640, np.float64(0.0)),
 (641, np.float64(0.0)),
 (642, np.float64(0.0)),
 (643, np.float64(0.0)),
 (644, np.float64(0.0)),
 (645, np.float64(0.0)),
 (646, np.float64(0.049690399499995326)),
 (647, np.float64(0.0)),
 (648, np.float64(0.0)),
 (649, np.float64(0.0)),
 (650, np.float64(0.0)),
 (651, np.float64(0.0)),
 (652, np.float64(0.0)),
 (653, np.float64(0.0)),
 (654, np.float64(0.0)),
 (655, np.float64(0.0)),
 (656, np.float64(0.0)),
 (657, np.float64(0.0)),
 (658, np.float64(0.0)),
 (659, np.float64(0.0)),
 (660, np.float64(0.0)),
 (661, np.float64(0.0)),
 (662, np.float64(0.0)),
 (663, np.float64(0.0)),
 (664, np.float64(0.0)),
 (665, np.float64(0.0)),
 (666, np.float64(0.0)),
 (667, np.float64(0.0)),
 (668, np.float64(0.0)),
 (669, np.float64(0.0)),
 (670, np.float64(0.0)),
 (671, np.float64(0.0)),
 (672, np.float64(0.06262242910851494)),
 (673, np.float64(0.0)),
 (674, np.float64(0.0)),
 (675, np.float64(0.0)),
 (676, np.float64(0.0)),
 (677, np.float64(0.0)),
 (678, np.float64(0.0)),
 (679, np.float64(0.0)),
 (680, np.float64(0.0)),
 (681, np.float64(0.0)),
 (682, np.float64(0.0)),
 (683, np.float64(0.0)),
 (684, np.float64(0.0)),
 (685, np.float64(0.0)),
 (686, np.float64(0.0)),
 (687, np.float64(0.0)),
 (688, np.float64(0.0)),
 (689, np.float64(0.0)),
 (690, np.float64(0.0)),
 (691, np.float64(0.0)),
 (692, np.float64(0.049690399499995326)),
 (693, np.float64(0.0)),
 (694, np.float64(0.0)),
 (695, np.float64(0.0)),
 (696, np.float64(0.0)),
 (697, np.float64(0.0)),
 (698, np.float64(0.0)),
 (699, np.float64(0.0)),
 (700, np.float64(0.0)),
 (701, np.float64(0.0)),
 (702, np.float64(0.0)),
 (703, np.float64(0.0)),
 (704, np.float64(0.0)),
 (705, np.float64(0.0)),
 (706, np.float64(0.0)),
 (707, np.float64(0.0)),
 (708, np.float64(0.0)),
 (709, np.float64(0.0)),
 (710, np.float64(0.0)),
 (711, np.float64(0.0)),
 (712, np.float64(0.0)),
 (713, np.float64(0.0)),
 (714, np.float64(0.0)),
 (715, np.float64(0.0)),
 (716, np.float64(0.0)),
 (717, np.float64(0.0)),
 (718, np.float64(0.0)),
 (719, np.float64(0.0)),
 (720, np.float64(0.0)),
 (721, np.float64(0.0)),
 (722, np.float64(0.0)),
 (723, np.float64(0.0)),
 (724, np.float64(0.0)),
 (725, np.float64(0.0)),
 (726, np.float64(0.0)),
 (727, np.float64(0.0)),
 (728, np.float64(0.0)),
 (729, np.float64(0.0)),
 (730, np.float64(0.0)),
 (731, np.float64(0.0)),
 (732, np.float64(0.0)),
 (733, np.float64(0.0)),
 (734, np.float64(0.0)),
 (735, np.float64(0.0)),

In [46]:
#index=0 ke pass me jo movie hai , uska index show below
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(3606, np.float64(0.24494897427831777)),
 (151, np.float64(0.18257418583505533)),
 (942, np.float64(0.17770466332772766)),
 (529, np.float64(0.16129556770910236)),
 (2405, np.float64(0.1438389904456152))]

In [47]:
def recommend(movie): ## doubt5
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [48]:
recommend('Avatar')

Apollo 18
Beowulf
The Book of Life
Tears of the Sun
Aliens

In [49]:
import pickle

In [50]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [51]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))